version: '3.9'
services:
  fake-cc-app:
    image: rdkk/coderdkk:fakecreditcard
    container_name: fake-cc-app
    depends_on:
      - database
      - vault
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - "spring.cloud.vault.host=vault"
      - "spring.cloud.vault.port=8200"
      - "spring.cloud.vault.uri=http://vault:8200"
      - "spring.cloud.vault.token=hvs.CAESIA6rOAPvZJjAirbt7bcgbQYei5LLydZ6kHb-2MuwWUQAGh4KHGh2cy45aTdPUmFDbTlRdTFET2dnQnFHeHFOYXo"
      - "spring.datasource.url=jdbc:postgresql://database:5432/finance"
  database:
    image: postgres
    container_name: postgres-db
    volumes:
#      - ./db/data:/var/lib/postgresql/data
      - ./db/initializedb.sql:/docker-entrypoint-initdb.d/initializedb.sql
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  vault:
    container_name: "vault"
    image: vault:1.13.3
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: ./vault/data/vault-init.sh
    volumes:
      - ./vault/config:/vault/config:rw
      - ./vault/policies:/vault/policies:rw
      - ./vault/data:/vault/data:rw
