openapi: 3.0.0
info:
  version: 1.0.0
  title: Fake Credit Card Generator Api

tags:
  - name: creditCard

paths:
  /finance/creditcard/fakegeneration:
    $ref: 'creditcard.yml#/paths/fake-generation'
  /finance/creditcard/fakegeneration/status:
    $ref: 'creditcard.yml#/paths/fake-generation-status'
  /finance/creditcard/fakegeneration/report:
    $ref: 'creditcard.yml#/paths/fake-generation-report'
